name: Terraform Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Install tfdocs
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -LO https://github.com/terraform-docs/terraform-docs/releases/download/v0.12.1/terraform-docs-v0.12.1-linux-amd64.tar.gz
          tar -xzf terraform-docs-v0.12.1-linux-amd64.tar.gz
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate Terraform docs
        run: terraform-docs markdown table . > README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update Terraform docs'
          git push
